### PR TITLE
Create configure_ubuntu.sh

### PR DESCRIPTION
**Pull request by tyqualters**
Initial set up script for Ubuntu. Note: If you accept this pull request, it is recommended that you `chmod +x` the file so that it's immediately executable upon cloning.

### CODE REVIEW

**Comment by ZechCodes** [comment]
This makes a lot of changes to a user's system that could potentially break their existing Python installation.

**Comment by tyqualters** [comment]
RE:
> This makes a lot of changes to a user's system that could potentially break their existing Python installation.

I've already tested this multiple times. I can promise you 9 times out of 10 it will not break a user's Python installation. Will lead to redundancies in their ~/.bashrc file if used multiple times on the same system, but will not lead to any breaking changes. This is the official way to install poetry and Python 3 / pip.
You could also comment out some of the ~/.bashrc pushes if you wanted to fix this entirely.
Of course, however, it's not my project so if you still feel unsafe with merging this pull request, by all means discard this change. It just makes it a hell of a lot easier setting up for first time users.

**Comment by ZechCodes** [comment]
If they have Python already setup this will change any aliases they have already configured. For example on my system python is aliased to use a stub that lets me change Python versions based on a dot file in each directory. Your script would break that.

I will not be merging any code that makes changes to the user's system.

**Comment by ZechCodes** [comment]
It also assumes users are using Bash. Many people are not.

**Pull request closed without merging**
